// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbCJ3yOd3Qnb05aDdbRnzk9SLyAxWoFjA',
    appId: '1:998918217945:web:95a9bf251bda7562451ec8',
    messagingSenderId: '998918217945',
    projectId: 'app-movies-b8c97',
    authDomain: 'app-movies-b8c97.firebaseapp.com',
    storageBucket: 'app-movies-b8c97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwli34igjB5jKElz8VrJkhOWcpqt6Nb3U',
    appId: '1:998918217945:android:26b2dd9308409629451ec8',
    messagingSenderId: '998918217945',
    projectId: 'app-movies-b8c97',
    storageBucket: 'app-movies-b8c97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeDsFSaVrQxuizp6qmVxyLwh5UMVtKSgU',
    appId: '1:998918217945:ios:e45b4214126f2af9451ec8',
    messagingSenderId: '998918217945',
    projectId: 'app-movies-b8c97',
    storageBucket: 'app-movies-b8c97.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeDsFSaVrQxuizp6qmVxyLwh5UMVtKSgU',
    appId: '1:998918217945:ios:e45b4214126f2af9451ec8',
    messagingSenderId: '998918217945',
    projectId: 'app-movies-b8c97',
    storageBucket: 'app-movies-b8c97.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbCJ3yOd3Qnb05aDdbRnzk9SLyAxWoFjA',
    appId: '1:998918217945:web:11c13417c8210559451ec8',
    messagingSenderId: '998918217945',
    projectId: 'app-movies-b8c97',
    authDomain: 'app-movies-b8c97.firebaseapp.com',
    storageBucket: 'app-movies-b8c97.appspot.com',
  );
}
